FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock (if it exists)
COPY package.json yarn.lock* ./

# Install dependencies
RUN npm install

# Copy public and src directories
COPY ./public ./public
COPY ./src ./src



# Expose port 3000
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
